"""remove models and add them in Song

Revision ID: 06489dc1a07f
Revises: 6b6cbe4e69fc
Create Date: 2022-04-17 22:31:08.525733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06489dc1a07f'
down_revision = '6b6cbe4e69fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_artist',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'artist_id')
    )
    op.create_table('song_featuring',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('featuring_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['featuring_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'featuring_id')
    )
    op.drop_table('song_to_artist')
    op.drop_table('song_to_featuring')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_to_featuring',
    sa.Column('song_id', sa.INTEGER(), nullable=False),
    sa.Column('featuring_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['featuring_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'featuring_id')
    )
    op.create_table('song_to_artist',
    sa.Column('song_id', sa.INTEGER(), nullable=False),
    sa.Column('artist_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'artist_id')
    )
    op.drop_table('song_featuring')
    op.drop_table('song_artist')
    # ### end Alembic commands ###
