"""fix typo of Album column total_length

Revision ID: 280e0ab2c72e
Revises: 52ef2d7b7f8d
Create Date: 2022-04-14 19:05:27.534697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280e0ab2c72e'
down_revision = '52ef2d7b7f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('total_length', sa.Time(), nullable=True))
    op.drop_column('album', 'total_lenght')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('total_lenght', sa.TIME(), nullable=True))
    op.drop_column('album', 'total_length')
    # ### end Alembic commands ###
