"""fix typo of Song column length

Revision ID: 52ef2d7b7f8d
Revises: d5085dd04bd8
Create Date: 2022-04-14 19:04:52.748126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ef2d7b7f8d'
down_revision = 'd5085dd04bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('length', sa.Time(), nullable=True))
    op.drop_column('song', 'lenght')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('lenght', sa.TIME(), nullable=True))
    op.drop_column('song', 'length')
    # ### end Alembic commands ###
