"""test

Revision ID: 6b6cbe4e69fc
Revises: 85414cd4e3fb
Create Date: 2022-04-17 22:20:11.322129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6cbe4e69fc'
down_revision = '85414cd4e3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('ee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ee', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
