"""test

Revision ID: 85414cd4e3fb
Revises: d77bb77a0bfc
Create Date: 2022-04-17 22:19:44.812554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85414cd4e3fb'
down_revision = 'd77bb77a0bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ee', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('ee')

    # ### end Alembic commands ###
