"""remove time total_length

Revision ID: b33b469c7d8f
Revises: 3ce35af1eb23
Create Date: 2022-04-16 14:37:47.717721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33b469c7d8f'
down_revision = '3ce35af1eb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('total_length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_length', sa.TIME(), nullable=True))

    # ### end Alembic commands ###
