"""add artist column to Album model

Revision ID: f6ba90625b95
Revises: 280e0ab2c72e
Create Date: 2022-04-14 20:04:41.334379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ba90625b95'
down_revision = '280e0ab2c72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('artist', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'artist')
    # ### end Alembic commands ###
